### ISSUE TITLE
XDG Directory specification compliance

### ISSUE THREAD

**Issue by Annwan** [Ara0n/pyscandl#10]
The database is always stored in `.local/share/` wheras it should only be stored there if the environment variable `XDG_DATA_HOME` isn't set, if said variable is set, it should be stored there instead

[ArchLinux Wiki for reference](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

**Comment by Ara0n** [comment]
done in 565ef288f819eb9aff5adda1d99bcd05c2eb01b1
