### ISSUE TITLE
GUI Crashes on launch when db is empty or inexistant

### ISSUE THREAD

**Issue by Annwan** [Ara0n/pyscandl#11]
**Describe the bug**
If the database is empty or doesn't exists, the GUI fails to load.

**To Reproduce**
 - Have an empty database (or no database at all)
 - Try to launch the GUI
 - See it fail

**Expected behavior**
The GUI should be able to launch despite a empty or non-existant database

**Version Info:**
 - OS: Garuda Linux (Arch based), KDE Plasma 5.21
 - Version: 3.0.0-b2
 - Installed via pip

**Comment by Ara0n** [comment]
done in 5ca68d139cbca7f5dbc4b4f0adf08e7b98a03e17
