### ISSUE TITLE
[SUGGESTION] Détection automatique du fetcher approprié

### ISSUE THREAD

**Issue by Annwan** [Ara0n/pyscandl#2]
Ce serait cool si le programme pouvait, lorsque que l'option `-l` est utilisée, détecter automatiquement le fetcher aproprié

**Comment by Ara0n** [comment]
will be done with the switch to docopt to parse the cli args
in the meantime wont be temporarily changed

**Comment by Ara0n** [comment]
Some websites might have the same domain and even the same links for multiple fetchers like mangadex with different languages or naver with all the collections. It renders it impossible to access some fetchers when not specifying the fetcher. Until it is shown that all the fetchers can be accessed with only the link it wont be done.
