### ISSUE TITLE
[SUGGESTION] end chapter flag

### ISSUE THREAD

**Issue by Annwan** [Ara0n/pyscandl#3]
Ce serait cool si le programme pouvait gérér le fait que l'utilisateur spécifie un chapitre de début, et un chapitre de fin

par exemple (si on suppose `-e` comme flag de chapitre de fin)
`python3 main.py -l <lien du manga> -f <nom du fetcher> -c 25 -e 37`
au lieu de
`python3 main.py -l <lien du manga> -f <nom du fetcher> -c 25 -n 12`

**Comment by Ara0n** [comment]
done with https://github.com/Ara0n/pyscandl/commit/4c94d188d85ac87454885ca4537bcc95824d22d6
