### ISSUE TITLE
Naver Webtoons or Daum Webtoons

### ISSUE THREAD

**Issue by jvalenteros** [Ara0n/pyscandl#4]
If it would be possible for Naver Webtoons or Daum Webtoons to be added to supported websites for download.

**Comment by Ara0n** [comment]
i'll look into it
once i do the fetcher rework for cleaner coding, so it's the next project in the line

**Comment by Ara0n** [comment]
Added support for naver comic, with all 3 tiers of webtoon, bestChallenge and challenge with release [2.4.1](https://github.com/Ara0n/pyscandl/releases/tag/2.4.1), it is also now on [PyPI](https://pypi.org/project/pyscandl/2.4.1/) if you want to pip install it. I'll close this issue until i start working on daum webtoons.
As I'm not a user of these sites i couldn't test them extensively so feel free to open an issue if a problem arise.
