### ISSUE TITLE
"|" character causes problems on windows

### ISSUE THREAD

**Issue by Bakareiki** [Ara0n/pyscandl#5]
**Describe the bug**
When a file name has the character "|" on windows, it causes the program to crash with an OSError and a TypeError.

**To Reproduce**
1. Download the sauce 321123 with the nhentai fetcher
2. See error

**Expected behavior**
The program crashes with 2 errors : an OSError and a TypeError

**Screenshots**
![image](https://user-images.githubusercontent.com/45868949/90241128-bed76000-de2a-11ea-9903-763502785325.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Ara0n** [comment]
fixed with commit https://github.com/Ara0n/pyscandl/commit/ded761bd5b854709
the illegal characters will now be replaced by █
